# Use the official .NET SDK image to build the app
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
# Set the working directory
WORKDIR /app
# Copy everything
COPY . ./
# Restore adn build the application
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Use the official .NET ASP.NET runtime image for the runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
# Set the working directory
WORKDIR /app
# Copy the build output from the build stage
COPY --from=build /app/out ./
# Expose the port the app runs on
EXPOSE 5005
# Set the environment variable for ASP.NET Core to listen on port 5001
ENV ASPNETCORE_URLS="http://*:5005"
# Start the application
ENTRYPOINT ["dotnet", "my-app.dll"]
